name: QA Pipeline

permissions:
  contents: read
  issues: write

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker network
        run: docker network create grid || true

      - name: Start Selenium Hub
        run: |
          docker run -d --rm --net grid --name selenium-hub \
            -p 4444:4444 -p 4442:4442 -p 4443:4443 \
            selenium/hub:latest

      - name: Start Chrome Node
        run: |
          docker run -d --rm --net grid --shm-size=2g \
            -e SE_EVENT_BUS_HOST=selenium-hub \
            -e SE_EVENT_BUS_PUBLISH_PORT=4442 \
            -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 \
            selenium/node-chrome:latest

      - name: Install jq (for JSON parsing)
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Wait for Selenium Grid to be ready
        run: |
          echo "Waiting for Selenium Grid to be ready..."
          for i in {1..15}; do
            STATUS=$(curl -s http://localhost:4444/status)
            echo "Raw STATUS: $STATUS"
            READY=$(echo "$STATUS" | jq -r '.value.ready')
            echo "Parsed ready status: '$READY'"

            if [ "$READY" = "true" ]; then
              echo "✅ Selenium Grid is ready."
              break
            fi

            echo "⏳ Not ready yet... sleeping 5s"
            sleep 5
          done

          if [ "$READY" != "true" ]; then
            echo "❌ Selenium Grid did not become ready in time"
            exit 1
          fi

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov jsonschema

      - name: Run functional tests
        run: |
          echo "Set PYTHONPATH to repo root"
          export PYTHONPATH=$(pwd)
          pytest tests/functional --cov=./ --cov-report=xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

      - name: Install k6
        run: |
          curl -fsSL https://dl.k6.io/key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/k6-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install -y k6

      - name: Run all k6 performance tests
        working-directory: ./tests/performance
        run: |
          for script in *.js; do
            echo "Running $script"
            k6 run "$script"
          done

      - name: Create reports/security folder
        run: mkdir -p reports/security

      - name: Set up OWASP ZAP (for security tests)
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: "https://jsonplaceholder.typicode.com"
          cmd_options: "-J reports/security/zap_report.json"
        continue-on-error: true

      - name: Upload ZAP JSON report
        uses: actions/upload-artifact@v4
        with:
          name: zap-security-json-report
          path: reports/security/zap_report.json

      - name: Run Selenium tests with Allure using Selenium Grid
        continue-on-error: true
        env:
          USE_SELENIUM_GRID: true
        run: |
          echo "Set PYTHONPATH to repo root"
          export PYTHONPATH=$(pwd)
          pytest tests/functional/selenium_tests/ --maxfail=0 --disable-warnings -v --alluredir=allure-results/selenium

      - name: Install Allure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jre
          curl -o allure-2.21.0.zip -L https://github.com/allure-framework/allure2/releases/download/2.21.0/allure-2.21.0.zip
          unzip -o allure-2.21.0.zip -d /opt/
          echo "/opt/allure-2.21.0/bin" >> $GITHUB_PATH
          echo "Allure version:"
          allure --version

      - name: Generate Allure report
        run: |
          if [ -d "allure-results/selenium" ]; then
            allure generate allure-results/selenium -o allure-results/selenium-report
          else
            echo "❌ Allure results directory not found!"
            exit 1
          fi

      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-results/selenium-report
